import { useState } from 'react';
import { router } from '@inertiajs/react';
import PrimaryButton from '@/Components/PrimaryButton';
import SecondaryButton from '@/Components/SecondaryButton';

export default function GenerateReminderModal({ invoice, show, onClose }) {
    const [isGenerating, setIsGenerating] = useState(false);
    const [streamedContent, setStreamedContent] = useState('');
    const [error, setError] = useState('');
    const [eventSource, setEventSource] = useState(null);

    const startGeneration = () => {
        setIsGenerating(true);
        setStreamedContent('');
        setError('');

        const url = route('ai.stream-reminder', invoice.id);
        const source = new EventSource(url);
        
        setEventSource(source);

        source.onmessage = (event) => {
            const data = JSON.parse(event.data);
            if (data.text) {
                setStreamedContent((prev) => prev + data.text);
            }
        };

        source.addEventListener('end', () => {
            source.close();
            setIsGenerating(false);
            
            // Reload the page to see the newly saved draft in the logs
            router.reload({ only: ['invoices'] });
        });

        source.addEventListener('error', (event) => {
            source.close();
            setIsGenerating(false);
            try {
                const data = JSON.parse(event.data);
                setError(data.message || 'An error occurred during generation.');
            } catch (e) {
                setError('Connection lost or error occurred.');
            }
        });
    };

    const handleClose = () => {
        if (eventSource) {
            eventSource.close();
        }
        setIsGenerating(false);
        setStreamedContent('');
        setError('');
        onClose();
    };

    if (!show) return null;

    return (
        <div className="modal fade show d-block" tabIndex="-1" style={{ backgroundColor: 'rgba(0, 0, 0, 0.5)' }}>
            <div className="modal-dialog modal-dialog-centered modal-lg">
                <div className="modal-content shadow">
                    <div className="modal-header border-bottom-0">
                        <h5 className="modal-title fw-bold">
                            ✨ AI Reminder Generator
                        </h5>
                        <button type="button" className="btn-close" onClick={handleClose} aria-label="Close"></button>
                    </div>
                    <div className="modal-body">
                        <p className="text-muted mb-4">
                            Invoice: <strong>{invoice?.invoice_number}</strong>
                            <br />
                            Click the button below to stream a payment reminder generated by Google Gemini.
                        </p>

                        {!isGenerating && !streamedContent && (
                            <PrimaryButton onClick={startGeneration}>
                                Generate Draft
                            </PrimaryButton>
                        )}

                        {error && (
                            <div className="alert alert-danger p-3 rounded mb-4 text-sm">
                                {error}
                            </div>
                        )}

                        {(streamedContent || isGenerating) && (
                            <div className="mt-4 p-4 bg-light border rounded" style={{ minHeight: '150px' }}>
                                <pre className="mb-0" style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>
                                    {streamedContent}
                                    {isGenerating && <span className="animate-pulse ms-1">▋</span>}
                                </pre>
                            </div>
                        )}
                    </div>
                    <div className="modal-footer border-top-0">
                        <SecondaryButton onClick={handleClose}>
                            Close
                        </SecondaryButton>
                    </div>
                </div>
            </div>
        </div>
    );
}
